<?php
$sLangName = 'Deutsch';
$aLang = [
    'charset' => 'UTF-8',

    'moOrderExport'                                => 'DHL Lieferadressen-Export',
    'MO_DHL__EXPORT_TITLE'                         => 'DHL Lieferadressen: CSV-Export',
    'MO_DHL__EXPORT'                               => 'Exportieren',
    'MO_DHL__EXPORT_ERROR_NO_ORDER_SELECTED'       => 'Bitte wählen Sie mindestens eine Bestellung aus.',
    'MO_DHL__EXPORT_ORDERS_WITHOUT_BILLING_NUMBER' => 'Für die Sendungen mit einer der folgenden Referenzen konnte keine Abrechnungsnummer erzeugt werden: %s',
    'MO_DHL__ORDER_DHL'                            => 'DHL',
    'MO_DHL__PROCESS_AND_PARTICIPATION'  => 'Verfahrens- und Teilnahmenummern',
    'MO_DHL__WUNSCHPAKET'                => 'Wunschpaket Optionen',
    'MO_DHL__WUNSCHTAG'                  => 'Wunschtag',
    'MO_DHL__WUNSCHZEIT'                 => 'Wunschzeit',
    'MO_DHL__WUNSCHORT'                  => 'Wunschort',
    'MO_DHL__WUNSCHNACHBAR'              => 'Wunschnachbar',
    'MO_DHL__EKP'                        => 'EKP',
    'MO_DHL__EKP_ERROR'                  => 'Eine EKP besteht aus genau zehn Ziffern.',
    'MO_DHL__PARTICIPATION_NUMBER'       => 'Teilnahmenummer',
    'MO_DHL__PARTICIPATION_NUMBER_ERROR' => 'Eine Teilnahmenummer besteht aus genau zwei Zeichen und enthält nur Buchstaben und Ziffern.',
    'MO_DHL__PROCESS_IDENTIFIER'         => 'Verfahrensnummer',
    'MO_DHL__PROCESS_IDENTIFIER_ERROR'   => 'Bitte wählen Sie eine Verfahrensnummer aus der Liste.',
    'MO_DHL__DELIVERYSET_DHL'            => 'DHL',
    'MO_DHL__DELIVERY_DHL'               => 'DHL',
    'MO_DHL__PAYMENTS_DHL'               => 'DHL',
    'MO_DHL__EXCLUDED'                   => 'Ausschließen',
    'MO_DHL_SAVE_AND_CHECK'              => 'Speichern und Zugangsdaten prüfen',
    'MO_DHL__CORRECT_CREDENTIALS'        => 'Zugangsdaten korrekt',
    'MO_DHL__INCORRECT_CREDENTIALS'      => 'Zugangsdaten inkorrekt. Bitte überprüfen Sie ihre Zugangsdaten.',
    'MO_DHL__LABELS'                     => 'Labels',
    'MO_DHL__LABEL'                      => 'Versandlabel',
    'MO_DHL__RETOURE_LABEL'              => 'Retourelabel',
    'MO_DHL__CREATE_LABEL'               => 'Neues Label erstellen',
];
