[{if $moEmpfaengerservicesSurchargeLabel}][{strip}]
    [{if $oViewConf->isFunctionalityEnabled('blShowVATForDelivery')}]
        [{oxmultilang ident=$moEmpfaengerservicesSurchargeLabel suffix='COLON'}] [{oxprice price=$moEmpfaengerservicesSurcharge->getNettoPrice() currency=$currency}]
        [{if $basket->isProportionalCalculationOn()}][{oxmultilang ident="BASKET_TOTAL_PLUS_PROPORTIONAL_VAT"}][{else}][{oxmultilang ident="VAT_PLUS_PERCENT_AMOUNT" suffix="COLON" args=$moEmpfaengerservicesSurcharge->getVat()}][{/if}][{oxprice price=$moEmpfaengerservicesSurcharge->getVatValue() currency=$currency}]
    [{else}]
        [{oxmultilang ident=$moEmpfaengerservicesSurchargeLabel suffix='COLON'}] [{oxprice price=$moEmpfaengerservicesSurcharge->getBruttoPrice() currency=$currency}]
    [{/if}]
[{/strip}][{/if}]
