[{if $oViewConf->isDhlFinderAvailable()}]
    [{assign var="moDHLGoogleMapsKey" value=$oViewConf->getGoogleMapsApiKey()}]
    [{oxscript include=$oViewConf->getModuleUrl("mo_dhl", "out/src/js/widgets/mo_dhl__finder.js") priority=9}]
    [{oxscript add='$(function() { if ($("#shippingAddressText").length) { mo_dhl__deliveryAddress.rearrangeAddress($("#shippingAddressText")); }});'}]
    [{block name="mo_dhl_theme_switch_finder"}]
        [{if $oViewConf->moHasAncestorTheme('azure')}]
            [{oxscript include=$oViewConf->getModuleUrl("mo_dhl", "out/src/js/widgets/azure/mo_dhl__finder.js") priority=9}]
            [{include file="mo_dhl__finder_azure.tpl"}]
        [{elseif $oViewConf->moHasAncestorTheme('flow')}]
            [{oxscript include=$oViewConf->getModuleUrl("mo_dhl", "out/src/js/widgets/flow/mo_dhl__finder.js") priority=9}]
            [{include file="mo_dhl__finder_flow.tpl"}]
        [{elseif $oViewConf->moHasAncestorTheme('wave')}]
            [{oxscript include=$oViewConf->getModuleUrl("mo_dhl", "out/src/js/widgets/flow/mo_dhl__finder.js") priority=9}]
            [{include file="mo_dhl__finder_wave.tpl"}]
        [{/if}]
        [{oxscript add='$(function() {  mo_dhl.initializeFinder("'|cat:$moDHLGoogleMapsKey|cat:'"); });'}]
    [{/block}]
[{/if}]
