[{* Include files needed for both the finder and Wunschpaktet *}]
[{oxstyle include=$oViewConf->getModuleUrl("mo_empfaengerservices", "out/src/css/widgets/mo_empfaengerservices.css")}]
[{oxscript include=$oViewConf->getModuleUrl("mo_empfaengerservices", "out/src/js/empfaengerservices.js") priority=9}]
[{oxscript include=$oViewConf->getModuleUrl("mo_empfaengerservices", "out/src/js/widgets/mo_empfaengerservices__deliveryAddress.js") priority=9}]
[{if $oViewConf->moHasAncestorTheme('azure')}]
    [{oxscript include="js/widgets/oxmodalpopup.js" priority=8}]
    [{oxscript include=$oViewConf->getModuleUrl("mo_empfaengerservices", "out/src/js/widgets/azure/empfaengerservices.js") priority=9}]
    [{oxscript include=$oViewConf->getModuleUrl("mo_empfaengerservices", "out/src/js/widgets/azure/empfaengerservices__validation.js") priority=10}]
[{elseif $oViewConf->moHasAncestorTheme('flow')}]
    [{oxscript include=$oViewConf->getModuleUrl("mo_empfaengerservices", "out/src/js/widgets/flow/empfaengerservices.js") priority=9}]
[{elseif $oViewConf->moHasAncestorTheme('wave')}]
    [{oxscript include=$oViewConf->getModuleUrl("mo_empfaengerservices", "out/src/js/widgets/wave/empfaengerservices.js") priority=9}]
[{/if}]
[{if $oView->getClassName() !== 'account_user'}]
    [{oxscript add='$(function() {  mo_empfaengerservices.initialize(true); });'}]
[{else}]
    [{oxscript add='$(function() {  mo_empfaengerservices.initialize(false); });'}]
[{/if}]
<p id="germany-oxid">[{$oViewConf->getGermanyId()}]</p>

[{* Module specific inclusions *}]
[{if $oViewConf->isDhlFinderAvailable()}]
    [{include file="mo_empfaengerservices__finder.tpl"}]
[{/if}]
[{include file="mo_empfaengerservices__wunschpaket.tpl"}]
