[{if $oView->getClassName() !== 'account_user'}]
    [{assign var="currency" value=$oView->getActCurrency()}]
    [{block name="mo_empfaengerservices_theme_switch_wunschpaket"}]
        [{if $oViewConf->moHasAncestorTheme('azure')}]
            [{include file="mo_empfaengerservices__wunschpaket_azure.tpl"}]
        [{elseif $oViewConf->moHasAncestorTheme('flow')}]
            [{include file="mo_empfaengerservices__wunschpaket_flow.tpl"}]
        [{elseif $oViewConf->moHasAncestorTheme('wave')}]
            [{include file="mo_empfaengerservices__wunschpaket_wave.tpl"}]
        [{/if}]
    [{/block}]

    [{oxscript include=$oViewConf->getModuleUrl("mo_empfaengerservices", "out/src/js/widgets/empfaengerservices__helperFunctions.js") priority=8}]
    [{oxscript include=$oViewConf->getModuleUrl("mo_empfaengerservices", "out/src/js/widgets/mo_empfaengerservices__wunschpaket.js") priority=8}]
    [{oxscript include=$oViewConf->getModuleUrl("mo_empfaengerservices", "out/src/js/widgets/empfaengerservices__validatorHelper.js") priority=9}]
    [{capture name='initialize' assign='initialize'}]
        $(function() { mo_empfaengerservices__wunschpaket.initializeWunschpaket("[{$oView->mo_empfaengerservices__getSelectedWunschzeitId()}]", "[{$oView->mo_empfaengerservices__getSelectedWunschtag()}]"); });
    [{/capture}]
    [{oxscript add=$initialize}]
[{/if}]
