[{if $oViewConf->isDhlFinderAvailable()}]
    [{oxscript include=$oViewConf->getModuleUrl("mo_empfaengerservices", "out/src/js/widgets/mo_empfaengerservices__finder.js") priority=9}]
    [{oxscript include="https://maps.googleapis.com/maps/api/js?libraries=geometry&key="|cat:$oViewConf->getGoogleMapsApiKey() priority=8}]
    [{oxscript add='$(function() { if ($("#shippingAddressText").length) { mo_empfaengerservices__deliveryAddress.rearrangeAddress($("#shippingAddressText")); }});'}]
    [{block name="mo_empfaengerservices_theme_switch_finder"}]
        [{if $oViewConf->moHasAncestorTheme('azure')}]
            [{oxscript include=$oViewConf->getModuleUrl("mo_empfaengerservices", "out/src/js/widgets/azure/empfaengerservices__finder.js") priority=9}]
            [{include file="mo_empfaengerservices__finder_azure.tpl"}]
        [{elseif $oViewConf->moHasAncestorTheme('flow')}]
            [{oxscript include=$oViewConf->getModuleUrl("mo_empfaengerservices", "out/src/js/widgets/flow/empfaengerservices__finder.js") priority=9}]
            [{include file="mo_empfaengerservices__finder_flow.tpl"}]
        [{elseif $oViewConf->moHasAncestorTheme('wave')}]
            [{oxscript include=$oViewConf->getModuleUrl("mo_empfaengerservices", "out/src/js/widgets/flow/empfaengerservices__finder.js") priority=9}]
            [{include file="mo_empfaengerservices__finder_wave.tpl"}]
        [{/if}]
        [{oxscript add='$(function() {  mo_empfaengerservices.initializeFinder(); });'}]
    [{/block}]
[{/if}]
